[package]
name = "spl-program-metadata-client"
version = "0.0.0"
description = "A generated Rust library for the Program Metadata program"
repository = "https://github.com/solana-program/program-metadata"
edition = "2021"
readme = "README.md"
license-file = "../../LICENSE"

[features]
test-sbf = []
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
borsh = "^0.10"
num-derive = "^0.3"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = "^2.2"
thiserror = "^1.0"
kaigan = { version = "^0.2", features = ["serde"] }

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "^2.2"
solana-sdk = "^2.2"
