[package]
name = "spl-program-metadata"
version = "0.0.0"
edition = "2021"
readme = "./README.md"
license-file = "../LICENSE"
publish = false

[package.metadata.solana]
program-id = "4FX3oHhpAkJcb2tFFrq9JBY8gc4RhCRM5g75VG9QHnj1"
program-dependencies = []
account-dependencies = []

[lib]
# TODO: split into program and interface crates
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.7.0"
pinocchio-pubkey = "0.2.2"
pinocchio-system = "0.2.1"

[dev-dependencies]
mollusk-svm = "0.1"
solana-sdk = "2.2"

[features]
logging = []
test-sbf = []
